### ISSUE TITLE
Unable to "Watch" videos on iOS 13 

### ISSUE THREAD

**Issue by the-real-adammork** [kashkashio/PopcornTimeTV#6]
App version:
iOS/tvOS version:

Make sure these boxes are checked before submitting your issue - thanks!

- [ ] If app was installed using **Cocoapods**, make sure the latest version of master has been cloned (`git reset --hard; git pull`). If app was installed by downloading an **.ipa** file, please make sure you have the [latest version](https://github.com/PopcornTimeTV/PopcornTimeTV/releases/latest) installed.
- [ ] You have done a quick search for your issue already (detailed one is not necessary). If you are in doubt, post it anyway, it's not too big of a deal.
- [ ] You have read the [Issue Contributing Guidelines](https://github.com/PopcornTimeTV/PopcornTimeTV/blob/master/CONTRIBUTING.md#issues) for this repository.

#### Expected Behaviour
Videos load after pick quality on an iPhone 11 Pro Max iOS 13
...

#### Actual Behaviour
pre-Loading screen  remains, unable to dismiss, and never transitions to loading and the actual video
...

#### Solution

I have a branch that fixes some of the issues and makes videos playable. I found new issues though with trying to re-watch the same video after an app exit. Willing to fix those in time, but for now maybe my branch is useful ?  How do I get collaboration access ?

**Comment by kashkashio** [comment]
Hi there and thanks for posting!
As far as i know on this repo those bugs are fixed.

Besides the bug on resume which sometimes causes the app crash due to error in torrent lib failing to load the resume data..

There is a workaround just clear cache from setting and you are good..

I will fix it soon.

I Think my branch is the most stable branch out there tough i’d be more than happy to get some help!
I will invite u as a collaborator or you can just open a pull request with ur suggested changes

**Comment by the-real-adammork** [comment]
Can you add me as a collaborator ? It wont let me push my branch to `origin`

<img width="798" alt="Screen Shot 2020-02-07 at 7 52 47 AM" src="https://user-images.githubusercontent.com/407743/74043804-e7b00180-497e-11ea-93a5-61964fb48028.png">

**Comment by the-real-adammork** [comment]
Made a PR

**Comment by the-real-adammork** [comment]
Made a PR - https://github.com/kashkashio/PopcornTimeTV/pull/7
